{ pkgs ? import <nixpkgs> { } }:

let
  php = pkgs.php85;

  # Only what this package's own composer.json autoloads (src/) plus the
  # manifest itself: no need for tests/, examples/, dotfiles, docs, etc. in
  # the composer path repository consumed by the build below.
  castorExtendedSrc = pkgs.lib.sourceByRegex ../. [
    "^composer\\.json$"
    "^src"
    "^src/.*"
  ];

  castorSrc = pkgs.fetchFromGitHub {
    owner = "jolicode";
    repo = "castor";
    tag = "v1.7.0";
    hash = "sha256-KxmNNvSHW67WwDJToteQI3NJmWGtNikOQVU8F+QUK/8=";
  };

  # castor's own composer.json/lock know nothing about this library: splice it
  # in as a path repository before the composer-vendor fixed-output
  # derivation locks and fetches dependencies.
  src = pkgs.runCommand "castor-with-castor-extended-src" {
    nativeBuildInputs = [ pkgs.jq ];
  } ''
    cp -r ${castorSrc} $out
    chmod -R u+w $out

    cp -r ${castorExtendedSrc} $out/castor-extended

    # Drop bump-after-update: it would silently rewrite composer.json's
    # constraints during the lock/vendor build, making that composer.json
    # diverge from the committed lock's validation hash.
    jq \
      '.repositories += [{"type": "path", "url": "./castor-extended", "options": {"symlink": false}}]
       | .require["mykiwi/castor-extended"] = "@dev"
       | del(.config."bump-after-update")' \
      $out/composer.json > $out/composer.json.tmp
    mv $out/composer.json.tmp $out/composer.json

    rm -f $out/composer.lock
  '';
in
php.buildComposerProject2 (finalAttrs: {
  pname = "castor-with-castor-extended";
  version = "1.7.0";

  inherit src;

  # Generated by a first `nix-build` attempt: castor's composer.json gets a
  # `mykiwi/castor-extended` path requirement spliced in above, which its
  # own upstream composer.lock knows nothing about, so a fresh lock has to
  # be committed for reproducible builds. Regenerate by deleting this file,
  # running `nix-build`, and copying the lock path printed in its error.
  composerLock = ./castor-with-castor-extended-composer.lock;

  vendorHash = "sha256-mXflTi7aeBdA0hmrIInuMA/qRPx3PcdcXRdyXtZfp88=";

  meta = {
    description = "Castor task runner, bundled with mykiwi/castor-extended's Target/Requires helpers";
    homepage = "https://github.com/mykiwi/castor-extended";
    license = pkgs.lib.licenses.mit;
    mainProgram = "castor";
  };
})
